# Generated by Django 4.0.2 on 2022-02-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='foto/%Y/%m/%d', verbose_name='Фотоверсия')),
            ],
            options={
                'verbose_name': 'Заметки',
                'verbose_name_plural': 'Заметки',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
